{% set name = "jupyterhub-ldapauthenticator" %}
{% set version = "1.3.0" %}
{% set sha256 = "920b115babdc32e7b159fc497a0a794bb0f57b222ce2c26c74a23594892f9d3c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools
  run:
    - python >=3.5
    - jupyterhub
    - ldap3
    - tornado
    - traitlets

test:
  imports:
    - ldapauthenticator

about:
  home: https://github.com/jupyterhub/ldapauthenticator
  license: BSD-3
  license_family: BSD
  license_file: LICENSE
  summary: 'LDAP Authenticator for JupyterHub'

extra:
  recipe-maintainers:
    - dhirschfeld
    - minrk
    - consideRatio
