# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "jC92B5mXoDETcIeTOAM+Qs/9V8cxAa22+cX1mNAHH999IlO3phb2fgwjjrXEBbCRk6PfuTPpnm4OmEcvMoKcH6OW9Ify8WuKjXeI6TOfP7iQWzuVlikewQ8mntBzAi7iAjoMoFDrZL1hVTqTE1SI+D/c3CIJ4zdjxmlH5evu3D7O586nSAWadQBX7ffqHRmkbBe55F+nO9Lp73pNLvq/cvxZkUfrK/D9woLb5sYjCArdGDFtTUYD+wP71gmKAiSXLFobX7rcgNxySHGY3PbVbwexF9dcb8M7D1oOn/72FnYeY+2+SZLZM2Dl+34PGi4nzjJDtrOTsOS2H4p3nXiHfvmNptGV30vbbYCsUlzTjMWfcy+km/dxESh52qjZPEboTgWXIpXXYklo0IwlPVpiNFUsdKXP0z7r9UekJF8iupHkKWmfmbqTeEGr/1tBXwKfQK3yqQ/uXHQXB+evIeI5hSgVKOb3BdAi79A1zuOp/kYrzKZfzURPCB9faQ/BdiR7QI+AO09nN5avV/q2tVI+9Dj2JnRPXCDerWG7F/CzXld5CvdWPNnXokyuH96Edigs6X9P3S2aKn7tPfDW5cmSqie7eUjciI+d9tNUWE1Iap+/1Mn+r/X9um7C8OPV8grA1U0xfhC3IGT+BXtyBE0OANvlzKh6vHIo3AtvFyap/fg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
