travis:
  secure:
    BINSTAR_TOKEN: uQ55zWjbL7wz5VtOgUfRJ837umjFDnMHRQ44WDpHxZfntyhwkBkT65ncuNGE8aifCLFyFUtVyZz9mofY7MIBUwG3pjvLb0WAm3JhccNgFrtVOpVG7ArwmqEh629lWM+d6R6c/dxsPf5Vwjii3hKRsAcHix7s02wmoOBGANly1mHFtNY8yrFqkUKtFtQGsVbtOmP3jZwEUAFpXFAKiwNueC2iTaVhY/QfOsy+ZuiO5R21WPLszR0VeQhKy0SpDQelxN9OCF6w8tBvHw5yJGzk6Q3QxqhHgE6YYu3PZFP341NBH9g80SPL/JLq9Ojj+2Ckq7rex3TN2TWxPriYLfnz+KyZNVnaYjUNbno5Kgjuc8gcBhkZRJbPDP59utyB3MPEdEJSgq9b/8iTGR6v061oFDEsOfr5HXzUiW3+98Q4Lpgm6sDPbYWoJAKCf9YyHc1DXXXiq67ohCCjw5AzDsNOCFktseEAIcpZAZd8SoCkSK3g4BidvVBv612mszQTPv17WQp9cFUG+x9Dx3/LlkZzKdmt6hASFgfN2F4MJ7CNWPo3raD9HdZTu50a1KRP2Ypvxzve+5AtW1aB1T/Pq2lDv3lsgM2IhXneqYMNsP8JIoLtQJQru/hjJphhrdKdoN07YeHrXA7f+vKpDaFXthJWSkZlMymNcX3yMNiMO8E0V2Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
