travis:
  secure:
    BINSTAR_TOKEN: DcUAs7Grit95dmvBO50uD2dLpuM35wMUoepmtIwZTZhWU0wE8gdBaXIZeKvMyBpsRr5D6gPdwnxXCRxyAe08pakh3QaF5qzUB20HfMxGL2Dch/00wRsv+HuFrKJFNrx1vJPESO7bRpJ/KrcKmoSGm1gavawezSA+7pHjPigGcntqMqxMgAXAFPHzj4iGY1VYdYbVHSMFDsgHGN5OLLzzEH+/CRScwuFpA1fb/yXtm8D63ul0x7E9XsQE6Kwao9R8/acq9U9aGRrB0DYzUhAMhPOVqqihhcvZFPXVoC47bcnBJEfMnFjoQRGtSm9Hsu72Olhw3s1dJA6xB5aDwJb7pTCo7aEULTq95nhkapv8Gt776RCw3BKMEF5jl0id/Biuke1XP/QhxKcM/G+PYWOqRKnvCjJuBlqP+Zq0nARSEJdjFlwGeDxXyJNYAQ+2QM6iZRyxruQ8/lbGS78WP9zQ1wGXmUKK2kQbOYxY+P0tn9ZzoqyFhJ+7PuGo+4tRmZubouOIi1fRBe0DvgxIwIIwZmE1h/jWoG+vm6uiJ8M98vRh0HhjEAaSz3CgyWLaFyZxh29Fz5LV8yLoEbsohJuULz3aikPndegGA93qQBoYN1PVJOFscC9zCgUU0B6fq/hVAeDqgcIiqrIH6znVethMOYKxKW1qd5rIiyaM5fX5QZQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
