appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: jC92B5mXoDETcIeTOAM+Qs/9V8cxAa22+cX1mNAHH999IlO3phb2fgwjjrXEBbCRk6PfuTPpnm4OmEcvMoKcH6OW9Ify8WuKjXeI6TOfP7iQWzuVlikewQ8mntBzAi7iAjoMoFDrZL1hVTqTE1SI+D/c3CIJ4zdjxmlH5evu3D7O586nSAWadQBX7ffqHRmkbBe55F+nO9Lp73pNLvq/cvxZkUfrK/D9woLb5sYjCArdGDFtTUYD+wP71gmKAiSXLFobX7rcgNxySHGY3PbVbwexF9dcb8M7D1oOn/72FnYeY+2+SZLZM2Dl+34PGi4nzjJDtrOTsOS2H4p3nXiHfvmNptGV30vbbYCsUlzTjMWfcy+km/dxESh52qjZPEboTgWXIpXXYklo0IwlPVpiNFUsdKXP0z7r9UekJF8iupHkKWmfmbqTeEGr/1tBXwKfQK3yqQ/uXHQXB+evIeI5hSgVKOb3BdAi79A1zuOp/kYrzKZfzURPCB9faQ/BdiR7QI+AO09nN5avV/q2tVI+9Dj2JnRPXCDerWG7F/CzXld5CvdWPNnXokyuH96Edigs6X9P3S2aKn7tPfDW5cmSqie7eUjciI+d9tNUWE1Iap+/1Mn+r/X9um7C8OPV8grA1U0xfhC3IGT+BXtyBE0OANvlzKh6vHIo3AtvFyap/fg=}
provider:
  linux: azure
  osx: azure
  win: azure